image: matspfeiffer/flutter:latest

stages:
  - build
  - analyze
  - test

before_script:
  # Installieren von Abhängigkeiten / Packages
  - echo "starting"
  - flutter pub get
  # build Ordner löschen
  - flutter clean

# Android App erstellen
build-android:
  stage: build
  script:
    - flutter build appbundle
    - echo "something"
  only:
    - develop

# iOS App erstellen
build-ios:
  stage: build
  script:
    - flutter build ios --no-codesign
    - cd build/ios/iphoneos
    - mkdir Payload
    - cd Payload
    - ln -s ../Runner.app
    - cd ..
    - zip -r app.ipa Payload
  only:
    - develop

# Web App erstellen
build-web:
  stage: build
  script:
    - flutter build web
    - cd build/web
    - zip -r web-app.zip .
  only:
    - develop

# Dart code anaylisieren
analyze:
  stage: analyze
  script:
    - flutter analyze --no-tafal-infos --no-fatal-warnings
  only:
    - develop

# Unit tests laufen lassen
unit_test:
  stage: test
  script:
    - flutter test --no-pub --coverage --test-randomize-ordering-seed random packages test
  only:
    - develop
