name: Build and deploy Flutter apps

# runs on every push on branch main
# TODO: analyze and test should run on other branches too
on:
  push:
    branches:
      - main

env:
  CACHE_FLUTTER: true # specify whether flutter should be cached or not
  BUILD_ANDROID: false # specify whether an android appbundle should be build or should be skipped
  BUILD_IOS: false
  BUILD_WEB: true
  BUILD_WINDOWS: false
  BUILD_LINUX: false
  BUILD_MACOS: false
  RELEASE: false

jobs:
  build:
    # build for iOS requires macOS underneath
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: $env.CACHE_FLUTTER
      - run: flutter --version # print flutter version

      - name: Install Packages / Dependencies
        run: flutter pub get

      - name: Analyze dart code
        run: flutter analyze lib test

      - name: Run tests including coverage
        # since packages has already been installed, --no-pub is used
        # --coverage collects code coverage of tests
        run: flutter test --no-pub --coverage test

      - name: Build Android Appbundle
        if: ${{ env.BUILD_ANDROID == 'true'}}
        run: flutter build appbundle

      - name: Build iOS App
        if: ${{ env.BUILD_IOS == 'true'}}
        run: |
            flutter build ios --no-codesign
            cd build/ios/iphoneos
            mkdir Payload
            cd Payload
            ln -s ../Runner.app
            cd ..
            zip -r app.ipa Payload

      - name: Build web
        if: ${{ env.BUILD_WEB == 'true'}}
        run: |
          flutter build web
          cd build/web
          zip -r web-app.zip .

      - name: Archive Web Production Artifact
        if: ${{ env.BUILD_WEB == 'true'}}
        uses: actions/upload-artifact@master
        with:
          name: web
          path: build/web

      - name: Build MacOS
        if: ${{ env.BUILD_MACOS == 'true'}}
        run: |
          flutter config --enable-macos-desktop
          flutter build macos

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: $env.CACHE_FLUTTER
      - run: flutter --version # print flutter version

      - name: Install Packages / Dependencies
        run: flutter pub get

      - name: Build Windows
        if: ${{ env.BUILD_WINDOWS == 'true'}}
        run: |
          flutter config --enable-windows-desktop
          flutter build windows

  build-linux:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            cache: $env.CACHE_FLUTTER
        - run: flutter --version # print flutter version

        - name: Install Packages / Dependencies
          run: flutter pub get

        - name: Build Linux
          if: ${{ env.BUILD_LINUX == 'true'}}
          run: |
            sudo apt-get update -y
            sudo apt-get install -y ninja-build libgtk-3-dev
            flutter config --enable-windows-desktop
            flutter build linux

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Release Apps
        if: ${{ env.RELEASE == 'true'}}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/**/*.apk,build/ios/iphoneos/app.ipa,build/web/web-app.zip'
